### PR TITLE
Update screenshot_analysis_status.csv

### PR DESCRIPTION
**Pull request by indigotran**
I added the reviewer column, added Etienne to the one he already did, and assigned myself 61 screenshots to do.

### CODE REVIEW

**Review by phylojenie — COMMENTED** [review]
Looks great, thanks Indigo

**Comment by indigotran** [comment]
@phylojenie Thanks! Good luck with the move tomorrow

**Comment by Crataegus9** [comment]
@phylojenie At least you will be moving out with decent temperatures! Wish you all the best!

**Comment by phylojenie** [comment]
Thank you both! Thanks for being so on top of the project stuff.

**Pull request merged**
