### PR TITLE
Emily_Added_Thoughts

### PR DESCRIPTION
**Pull request by EKROFT**
Added a thought on the last research question

### CODE REVIEW

**Review by indigotran — APPROVED** [review]

**Review by phylojenie — APPROVED** [review]

**Review by Crataegus9 — APPROVED** [review]

**Review by aliczner — COMMENTED** [review]
Plants would be good to include like the anemone the clown fish live in at the beginning of the movie, that would be an example of an accurate mutualism represented in the movie

**Comment by EKROFT** [comment]
> Plants would be good to include like the anemone the clown fish live in at the beginning of the movie, that would be an example of an accurate mutualism represented in the movie

ok, animals and plants then?

**Comment by Crataegus9** [comment]
Anemones are animals by the way ;)
I don’t think any algae in the movie can be reliably identified, so maybe we should stick to just animals.

**Comment by aliczner** [comment]
> Anemones are animals by the way ;)
> I don’t think any algae in the movie can be reliably identified, so maybe we should stick to just animals.

LOL I just realized I said anemones are plants and had to sign in now to correct this but TY for correcting this for me

**Comment by Crataegus9** [comment]
No worries!

**Pull request merged**
